In [ ]:
import numpy as np

A = np.identity(3)
B = np.ones(9).reshape(3, 3)
x = np.array([1, 2, 3]).T

y = np.zeros(3).T

y += (A@B)@x
y.sum()

In [ ]:
from numpy import double


file = open("../Data/Line/position.txt", "r")
lines = file.readlines()

lines = [line.replace('\n','') for line in lines]
lines


In [39]:
a = np.array([1, 1, 1]).T
b = np.array([1, 1, 1])
c = a@b
print(c)

3


In [49]:
c = np.array([[1 , 1], [1, 2]]) @ [2, 0]
c

array([2, 2])

In [7]:
a = []
b = [ 2, 3,]
c = [ 2, 3,]
a.append(b)
a.append(c)
print(int(9/2))

4


In [8]:
import numpy as np

a = [1, 2, 3, 4, 5, 6]

m = np.array([[-0.02986818,  0.43759146 , 0.8986777 , -0.3969707 ],
            [ 0.12236504 , 0.89391709, -0.43120649, -0.460018  ],
            [-0.99203563 , 0.09708738, -0.08024557,  0.3899877 ],
            [ 0.         , 0.        ,  0.        , 1.        ]])


n = np.linalg.inv(m)

point_m = np.array([1, 1, 1, 1]).reshape(4, 1)

print(point_m)

point_n = m@point_m

print(n@point_n)




[[1]
 [1]
 [1]
 [1]]
[[1.]
 [1.]
 [1.]
 [1.]]


In [2]:
import numpy as np

a = np.array([[-5.64466680e-01 , 3.96051085e+00 , 1.78352519e+00 ,-5.15631980e+03],
        [ 2.86267808e+00 ,-1.13607758e+00,  1.90606287e+00 ,-8.38560139e+02],
        [-4.38447667e+00 ,-2.99201810e+00,  1.47552702e+00 ,-6.00595805e+02],
        [ 0.00000000e+00 , 0.00000000e+00,  0.00000000e+00 , 0.00000000e+00]])

print(a.sum())

-6592.56447902


In [10]:
import numpy as np 

a = np.random.random(15).reshape(5, 3)
print(a)
b = np.mean(a, axis=0)
print(np.square(a - b).sum())

[[0.86872571 0.43925764 0.85425195]
 [0.41357451 0.48042506 0.17842261]
 [0.35606126 0.50766893 0.63212894]
 [0.70104461 0.1378353  0.42628169]
 [0.58815938 0.84265787 0.90627626]]
0.7941713524651375


In [11]:
import numpy as np

a = np.ndarray([1, 1, 1])
b = np.mean(a)
b

-3.773997756807905e-33

In [3]:
import threading

def calculate_square(numbers):
    for n in numbers:
        print("Square of", n, "is", n*n)

def calculate_cube(numbers):
    for n in numbers:
        print("Cube of", n, "is", n*n*n)

# 创建线程
numbers = [2, 3, 4, 5]
funcs = [calculate_square, calculate_cube]
for func in funcs:
    threading.Thread(target=calculate_square, args=(numbers,)).start()

print("All threads finished")


Square of 2 is 4
Square of 3 is 9
Square of 4 is 16
Square of 5 is 25
Square of 2 is 4
Square of 3 is 9
Square of 4 is 16
Square of 5 is 25
All threads finished


In [1]:
a = [1, "2", {'c': 4}]
a

[1, '2', {'c': 4}]

In [2]:
import numpy as np
a = np.array([0, 0, 50])
b = np.array([10, 0, 0])
a@b


0

In [4]:
a = {'c': 1}

a['b'] = 3453

print(a)

{'c': 1, 'b': 3453}
