In [ ]:
import numpy as np

A = np.identity(3)
B = np.ones(9).reshape(3, 3)
x = np.array([1, 2, 3]).T

y = np.zeros(3).T

y += (A@B)@x
y.sum()

In [ ]:
from numpy import double


file = open("../Data/Line/position.txt", "r")
lines = file.readlines()

lines = [line.replace('\n','') for line in lines]
lines


In [39]:
a = np.array([1, 1, 1]).T
b = np.array([1, 1, 1])
c = a@b
print(c)

3


In [49]:
c = np.array([[1 , 1], [1, 2]]) @ [2, 0]
c

array([2, 2])

In [7]:
a = []
b = [ 2, 3,]
c = [ 2, 3,]
a.append(b)
a.append(c)
print(int(9/2))

4


In [8]:
import numpy as np

a = [1, 2, 3, 4, 5, 6]

m = np.array([[-0.02986818,  0.43759146 , 0.8986777 , -0.3969707 ],
            [ 0.12236504 , 0.89391709, -0.43120649, -0.460018  ],
            [-0.99203563 , 0.09708738, -0.08024557,  0.3899877 ],
            [ 0.         , 0.        ,  0.        , 1.        ]])


n = np.linalg.inv(m)

point_m = np.array([1, 1, 1, 1]).reshape(4, 1)

print(point_m)

point_n = m@point_m

print(n@point_n)




[[1]
 [1]
 [1]
 [1]]
[[1.]
 [1.]
 [1.]
 [1.]]


In [2]:
import numpy as np

a = np.array([[-5.64466680e-01 , 3.96051085e+00 , 1.78352519e+00 ,-5.15631980e+03],
        [ 2.86267808e+00 ,-1.13607758e+00,  1.90606287e+00 ,-8.38560139e+02],
        [-4.38447667e+00 ,-2.99201810e+00,  1.47552702e+00 ,-6.00595805e+02],
        [ 0.00000000e+00 , 0.00000000e+00,  0.00000000e+00 , 0.00000000e+00]])

print(a.sum())

-6592.56447902


In [10]:
import numpy as np 

a = np.random.random(15).reshape(5, 3)
print(a)
b = np.mean(a, axis=0)
print(np.square(a - b).sum())

[[0.86872571 0.43925764 0.85425195]
 [0.41357451 0.48042506 0.17842261]
 [0.35606126 0.50766893 0.63212894]
 [0.70104461 0.1378353  0.42628169]
 [0.58815938 0.84265787 0.90627626]]
0.7941713524651375


In [11]:
import numpy as np

a = np.ndarray([1, 1, 1])
b = np.mean(a)
b

-3.773997756807905e-33

In [3]:
import threading

def calculate_square(numbers):
    for n in numbers:
        print("Square of", n, "is", n*n)

def calculate_cube(numbers):
    for n in numbers:
        print("Cube of", n, "is", n*n*n)

# 创建线程
numbers = [2, 3, 4, 5]
funcs = [calculate_square, calculate_cube]
for func in funcs:
    threading.Thread(target=calculate_square, args=(numbers,)).start()

print("All threads finished")


Square of 2 is 4
Square of 3 is 9
Square of 4 is 16
Square of 5 is 25
Square of 2 is 4
Square of 3 is 9
Square of 4 is 16
Square of 5 is 25
All threads finished


In [1]:
a = [1, "2", {'c': 4}]
a

[1, '2', {'c': 4}]

In [2]:
import numpy as np
a = np.array([0, 0, 50])
b = np.array([10, 0, 0])
a@b


0

In [8]:
import numpy as np
print(np.linalg.norm(np.array([779.43032994, 905.97572392, 648.01058605]) - np.array([-50.         , 50.  ,        44.73177898])))

1335.8871326667338


In [1]:
func = lambda x, y, z: x+y*z

print(func(1, 2, 3))

7


In [4]:
import numpy as np

def are_vectors_coplanar(vector_a, vector_b):
    # 将向量转换为NumPy数组
    a = np.array(vector_a)
    b = np.array(vector_b)

    # 计算向量的叉乘
    cross_product = np.cross(a, b)

    # 如果叉乘结果是零向量，则说明两个向量共面
    return np.allclose(cross_product, np.zeros_like(cross_product))

# 示例向量
vector1 = [-5, 0, 3]
vector2 = [5, 0, 6]

# 检查两个向量是否共面
result = are_vectors_coplanar(vector1, vector2)

if result:
    print("两个向量共面。")
else:
    print("两个向量不共面。")


两个向量不共面。


In [2]:
import math
plane_coefficients = [-0.2921517768151719, -0.05536545016810942, -0.9547680379188552, +12.261637793739581]
point = [26.10260100960182, -8.115628611870187, 5.325944898474351]
# 提取平面方程的系数
A, B, C, D = plane_coefficients

# 提取点的坐标
x0, y0, z0 = point

# 计算点到平面的距离
distance = abs(A*x0 + B*y0 + C*z0 + D) / math.sqrt(A**2 + B**2 + C**2)

print(f'平面方程：{A}x+{B}y+{C}z+{D}, 点坐标{x0, y0, z0}')
print(f'点到平面距离{distance}')


平面方程：-0.2921517768151719x+-0.05536545016810942y+-0.9547680379188552z+12.261637793739581, 点坐标(26.10260100960182, -8.115628611870187, 5.325944898474351)
点到平面距离0.0


In [4]:
import numpy as np

def point_to_plane_distance(point, plane):
    """
    计算三维空间中一个点到平面的距离
    :param point: 点的坐标，格式为[x, y, z]
    :param plane: 平面的参数方程，格式为[A, B, C, D]
    :return: 点到平面的距离
    """
    A, B, C, D = plane
    x, y, z = point
    distance = abs(A * x + B * y + C * z + D) / np.sqrt(A ** 2 + B ** 2 + C ** 2)
    print(abs(A * x + B * y + C * z + D))
    print(np.sqrt(A ** 2 + B ** 2 + C ** 2))
    return distance

# 平面方程：-0.5079998157816661x - 0.43831107144015674y - 0.7414982075627526z + 14.133206716600318
# 点坐标：(25.498912686208477, -10.950004932228685, 8.06377156749601)
plane = [-0.5079998157816661, -0.43831107144015674, -0.7414982075627526, 14.133206716600318]
point = [25.498912686208477, -10.950004932228685, 8.06377156749601]

distance = point_to_plane_distance(point, plane)
print("点到平面的距离为：", distance)


0.0
1.0
点到平面的距离为： 0.0


In [16]:
import inspect
import re

funList = []
for i in range(10):
    funList.append(lambda a: fun(a, i))
def fun(a, x):
    print(a, x)
print(funList)
for i in range(10):
    funList[i]("sssss")

[<function <lambda> at 0x000002AB3E316E50>, <function <lambda> at 0x000002AB3E316EE0>, <function <lambda> at 0x000002AB3E316F70>, <function <lambda> at 0x000002AB3E323040>, <function <lambda> at 0x000002AB3E3230D0>, <function <lambda> at 0x000002AB3E323160>, <function <lambda> at 0x000002AB3E3231F0>, <function <lambda> at 0x000002AB3E323280>, <function <lambda> at 0x000002AB3E323310>, <function <lambda> at 0x000002AB3E3913A0>]


IndexError: tuple index out of range

In [4]:
a = {'c': 1}

a['b'] = 3453

print(a)

{'c': 1, 'b': 3453}
